apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: merrygit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: merrygit-frontend:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_USER_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: merrygit-config
                  key: NEXT_PUBLIC_USER_API_BASE_URL
            - name: NEXT_PUBLIC_CHAT_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: merrygit-config
                  key: NEXT_PUBLIC_CHAT_API_BASE_URL
            - name: NEXT_PUBLIC_SOCKET_URL
              valueFrom:
                configMapKeyRef:
                  name: merrygit-config
                  key: NEXT_PUBLIC_SOCKET_URL
            - name: NEXT_PUBLIC_GITHUB_REPO_URL
              valueFrom:
                configMapKeyRef:
                  name: merrygit-config
                  key: NEXT_PUBLIC_GITHUB_REPO_URL
            - name: NEXT_PUBLIC_GITHUB_API_URL
              valueFrom:
                configMapKeyRef:
                  name: merrygit-config
                  key: NEXT_PUBLIC_GITHUB_API_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: merrygit-secret
                  key: JWT_SECRET