apiVersion: v1
kind: Secret
metadata:
  name: merrygit-secret
  namespace: merrygit
type: Opaque
stringData:
  # JWT
  JWT_SECRET: "your_jwt_secret_here"

  # MongoDB
  MONGO_URI: "mongodb+srv://username:password@cluster.mongodb.net/dbname"

  # Cloudinary
  CLOUDINARY_CLOUD_NAME: "your_cloud_name_here"
  CLOUDINARY_API_KEY: "your_api_key_here"
  CLOUDINARY_API_SECRET: "your_api_secret_here"

  # RabbitMQ
  RABBITMQ_URL: "amqp://username:password@host:5672"

  # RABBITMQ_HOST: "your_rabbitmq_host_here"
  # RABBITMQ_USERNAME: "your_rabbitmq_username_here"
  # RABBITMQ_PASSWORD: "your_rabbitmq_password_here"

  # Redis
  REDIS_HOST: "your_redis_host_here"
  REDIS_PASSWORD: "your_redis_password_here"
  REDIS_USER: "your_redis_user_here"

  # Resend
  RESEND_API_KEY: "re_your_resend_api_key_here"