apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: merrygit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: merrygit-user:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: merrygit-config
                  key: NODE_ENV
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: merrygit-config
                  key: FRONTEND_URL
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: merrygit-secret
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: merrygit-secret
                  key: JWT_SECRET
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: merrygit-secret
                  key: RABBITMQ_URL
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: merrygit-secret
                  key: RABBITMQ_HOST
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: merrygit-secret
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: merrygit-secret
                  key: RABBITMQ_PASSWORD
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: merrygit-secret
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: merrygit-secret
                  key: CLOUDINARY_API_KEY
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: merrygit-secret
                  key: CLOUDINARY_API_SECRET
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: merrygit-secret
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: merrygit-config
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: merrygit-secret
                  key: REDIS_PASSWORD
            - name: REDIS_USER
              valueFrom:
                secretKeyRef:
                  name: merrygit-secret
                  key: REDIS_USER